{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: plataforma-solicitudes
data:
{{ toYaml $svc.config | indent 2 }}
{{- end }}
